# Generated by Django 4.1.7 on 2023-04-18 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('owner', '0005_alter_property_create_date_alter_property_item_list_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='damage',
            name='item',
        ),
        migrations.AddField(
            model_name='damage',
            name='item_id',
            field=models.IntegerField(null=True),
        ),
    ]
