# Generated by Django 4.1.7 on 2023-04-05 02:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='choice',
            name='ugh',
            field=models.IntegerField(default=0),
        ),
    ]
